import Image from "next/image";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { ThemeProvider } from "@/components/theme-provider"
import { ModeToggle } from "@/components/mode-toggle"
import { useTheme } from "next-themes"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Void Pixel",
    description: "Generated by create next app",
};

export default function Home() {
    return (
        <body className={inter.className}>
            <div className="flex items-center overflow-hidden justify-between m-4 max-w-screen">
                <div className="flex items-center">
                    <Avatar>
                        <AvatarImage src="https://github.com/shadcn.png" />
                        <AvatarFallback>CN</AvatarFallback>
                    </Avatar>
                    <span className="ml-3">User</span> 
                </div>
                <div className="flex flex-grow justify-center">
                    <Input type="text" className="px-3 py-2 w-1/2" placeholder="Search..." />
                    <Button className="ml-2 px-3 py-2">Search</Button>
                </div>
                <div className="text-right">Void Pixel</div>
            </div>
            <div className="flex ml-30">
                <ModeToggle />
            </div>
        </body>
    );
}
